### ISSUE TITLE
Can't update to 0.0.2

### ISSUE THREAD

**Issue by MarshmallowCirno** [StoyanDimitrov/middle-mouse-button-scroll#2]
For some reason I can't install new update from addons.mozilla.org. Firefox says that addon downloaded from website cannon be installed because it appears to be corrupt. I'm using latest nightly

**Comment by StoyanDimitrov** [comment]
New version, fixing the corruption just has been approved. Autoupdate will kick in in a day or so. Thank you for reporting.
