### ISSUE TITLE
Add option to keep the cursor stationary while scrolling

### ISSUE THREAD

**Issue by Keith94** [StoyanDimitrov/middle-mouse-button-scroll#3]

**Comment by StoyanDimitrov** [comment]
Can you provide me with example behaviour or more detailed description of the feature request?

**Comment by Keith94** [comment]
I prefer if the cursor (with four arrows) that appears when middle mouse scrolling to stay in the same location on the screen without being affected by moving the mouse ourselves. I hope that helps.
